# Generated by Django 3.2 on 2021-04-24 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='adsress',
            new_name='address',
        ),
    ]
